query FeedbackDiscussion(
  $ids: [ID!]!
  $comments: Int!
  $includeComments: Boolean!
  $includeLabels: Boolean!
  $includeLink: Boolean!
  $includeReactions: Boolean!
  $includeAnswers: Boolean!
  $includePolls: Boolean!
  $includeAuthors: Boolean!
  $includeModeration: Boolean!
  $includeCommentReactions: Boolean!
) {
  nodes(ids: $ids) {
    ... on Discussion {
      id
      number
      title
      body
      bodyHTML
      createdAt
      author @include(if: $includeAuthors) { login avatarUrl ... on User { id } }
      authorAssociation @include(if: $includeAuthors)
      url @include(if: $includeLink)
      repository { id }
      category { id name }
      labels(first: 100) @include(if: $includeLabels) { nodes { id name color description } }
      reactionGroups @include(if: $includeReactions) { content reactors { totalCount } }
      poll @include(if: $includePolls) {
        question
        totalVoteCount
        options(first: 100) { nodes { id option totalVoteCount } }
      }
      answer @include(if: $includeAnswers) { id }
      comments(first: $comments) @include(if: $includeComments) {
        totalCount
        pageInfo { hasNextPage endCursor }
        nodes {
          id body bodyHTML
          url @include(if: $includeLink)
          author @include(if: $includeAuthors) { login avatarUrl ... on User { id } }
          authorAssociation @include(if: $includeAuthors)
          createdAt updatedAt deletedAt
          isMinimized
          minimizedReason @include(if: $includeModeration)
          isAnswer @include(if: $includeAnswers)
          reactionGroups @include(if: $includeCommentReactions) { content reactors { totalCount } }
          replies(first: $comments) {
            totalCount
            pageInfo { hasNextPage endCursor }
            nodes {
              id body bodyHTML
              url @include(if: $includeLink)
              author @include(if: $includeAuthors) { login avatarUrl ... on User { id } }
              authorAssociation @include(if: $includeAuthors)
              createdAt updatedAt deletedAt
              isMinimized
              minimizedReason @include(if: $includeModeration)
              reactionGroups @include(if: $includeCommentReactions) { content reactors { totalCount } }
            }
          }
        }
      }
    }
  }
}
