mutation FeedbackVote(
  $id: ID!
  $removeUp: Boolean!
  $removeDown: Boolean!
  $addUp: Boolean!
  $addDown: Boolean!
) {
  removeUp: removeReaction(input: {subjectId: $id, content: THUMBS_UP})
    @include(if: $removeUp) { subject { ...FeedbackReactions } }
  removeDown: removeReaction(input: {subjectId: $id, content: THUMBS_DOWN})
    @include(if: $removeDown) { subject { ...FeedbackReactions } }
  addUp: addReaction(input: {subjectId: $id, content: THUMBS_UP})
    @include(if: $addUp) { subject { ...FeedbackReactions } }
  addDown: addReaction(input: {subjectId: $id, content: THUMBS_DOWN})
    @include(if: $addDown) { subject { ...FeedbackReactions } }
}

fragment FeedbackReactions on Reactable {
  reactionGroups {
    content
    users { totalCount }
    viewerHasReacted
  }
}
